import { prisma } from "@/lib/prisma";
import { Difficulty } from "@prisma/client";

const challenges = [
  // --- JAVASCRIPT ---
  {
    title: "Soma de Dois Números",
    slug: "soma-de-dois-numeros",
    language: "javascript",
    description: "Crie uma função chamada `solution` que receba dois números e retorne a soma deles.",
    difficulty: Difficulty.EASY,
    points: 10,
    hints: ["Use o operador +", "Lembre do return"],
    solution: "function solution(a, b) { return a + b; }",
    explanation: "Soma simples de dois inteiros.",
    tags: ["javascript", "iniciante"],
    testCases: [
      { input: "2, 3", expected: "5", isHidden: false },
    ],
  },
  // --- SHELL (Piscine) ---
  {
    title: "Ex 01: Only the best know Z",
    slug: "ex01-z",
    language: "bash",
    description: "Crie um arquivo chamado `z` (ou apenas dê o comando `cat z`) que retorne 'Z' seguido de uma quebra de linha.",
    difficulty: Difficulty.EASY,
    points: 5,
    hints: ["Use echo Z"],
    solution: "echo Z",
    explanation: "Basta imprimir Z.",
    tags: ["bash", "piscine"],
    testCases: [
      { input: "", expected: "Z", isHidden: false },
    ],
  },
  {
    title: "Ex 03: find_sh",
    slug: "ex03-find-sh",
    language: "bash",
    description: "Escreva uma linha de comando que procure todos os nomes de arquivos que terminam com '.sh' no diretório atual e subdiretórios, exibindo apenas o nome sem a extensão.",
    difficulty: Difficulty.MEDIUM,
    points: 10,
    hints: ["Use find", "Use basename ou sed"],
    solution: "find . -type f -name \"*.sh\" -exec basename {} .sh \\;",
    explanation: "Combina find com basename para limpar a extensão.",
    tags: ["bash", "piscine"],
    testCases: [
      { input: "", expected: "find_sh", isHidden: false },
    ],
  },
  // --- C (Piscine) ---
  {
    title: "Ex 06: ft_print_alphabet",
    slug: "ex06-ft-print-alphabet",
    language: "c",
    description: "Exiba o alfabeto em minúsculas em ordem crescente.\n\n`void ft_print_alphabet(void);`",
    difficulty: Difficulty.EASY,
    points: 10,
    hints: ["Loop de 'a' até 'z'"],
    solution: "void ft_putchar(char c);\nvoid ft_print_alphabet(void) { char c = 'a'; while(c<='z') ft_putchar(c++); }",
    explanation: "Loop simples de caracteres.",
    tags: ["c", "piscine"],
    testCases: [{ input: "ft_print_alphabet();", expected: "abcdefghijklmnopqrstuvwxyz", isHidden: false }],
  },
  {
    title: "Ex 07: ft_print_numbers",
    slug: "ex07-ft-print-numbers",
    language: "c",
    description: "Exiba todos os dígitos em ordem crescente.\n\n`void ft_print_numbers(void);`",
    difficulty: Difficulty.EASY,
    points: 10,
    hints: ["Loop de '0' até '9'"],
    solution: "void ft_putchar(char c);\nvoid ft_print_numbers(void) { char c = '0'; while(c<='9') ft_putchar(c++); }",
    explanation: "Loop de dígitos.",
    tags: ["c", "piscine"],
    testCases: [{ input: "ft_print_numbers();", expected: "0123456789", isHidden: false }],
  },
  {
    title: "Ex 08: ft_is_negative",
    slug: "ex08-ft-is-negative",
    language: "c",
    description: "Exiba 'N' se n for negativo, ou 'P' se positivo ou nulo.\n\n`void ft_is_negative(int n);`",
    difficulty: Difficulty.EASY,
    points: 10,
    hints: ["if (n < 0)"],
    solution: "void ft_putchar(char c);\nvoid ft_is_negative(int n) { if(n<0) ft_putchar('N'); else ft_putchar('P'); }",
    explanation: "Condicional básica.",
    tags: ["c", "piscine"],
    testCases: [
      { input: "ft_is_negative(-1);", expected: "N", isHidden: false },
      { input: "ft_is_negative(42);", expected: "P", isHidden: false },
    ],
  },
  {
    title: "Ex 09: ft_ft",
    slug: "ex09-ft-ft",
    language: "c",
    description: "Atribua 42 ao inteiro apontado pelo parâmetro.\n\n`void ft_ft(int *nbr);`",
    difficulty: Difficulty.EASY,
    points: 10,
    hints: ["*nbr = 42"],
    solution: "void ft_ft(int *nbr) { *nbr = 42; }",
    explanation: "Ponteiros básicos.",
    tags: ["c", "piscine"],
    testCases: [{ input: "int n=0; ft_ft(&n); printf(\"%d\", n);", expected: "42", isHidden: false }],
  },
  {
    title: "Ex 10: ft_swap",
    slug: "ex10-ft-swap",
    language: "c",
    description: "Troque o valor de dois inteiros.\n\n`void ft_swap(int *a, int *b);`",
    difficulty: Difficulty.EASY,
    points: 10,
    hints: ["Use uma variável temp"],
    solution: "void ft_swap(int *a, int *b) { int t=*a; *a=*b; *b=t; }",
    explanation: "Swap usando ponteiros.",
    tags: ["c", "piscine"],
    testCases: [{ input: "int a=1, b=2; ft_swap(&a,&b); printf(\"%d %d\",a,b);", expected: "2 1", isHidden: false }],
  },
  {
    title: "Ex 11: ft_div_mod",
    slug: "ex11-ft-div-mod",
    language: "c",
    description: "Divide a por b, armazena em div e o resto em mod.\n\n`void ft_div_mod(int a, int b, int *div, int *mod);`",
    difficulty: Difficulty.EASY,
    points: 10,
    hints: ["*div = a / b"],
    solution: "void ft_div_mod(int a, int b, int *div, int *mod) { *div = a/b; *mod = a%b; }",
    explanation: "Operações aritméticas com ponteiros.",
    tags: ["c", "piscine"],
    testCases: [{ input: "int d,m; ft_div_mod(13,5,&d,&m); printf(\"%d %d\",d,m);", expected: "2 3", isHidden: false }],
  },
  {
    title: "Ex 12: ft_iterative_factorial",
    slug: "ex12-ft-iterative-factorial",
    language: "c",
    description: "Fatorial iterativo. Retorne 0 em erro.\n\n`int ft_iterative_factorial(int nb);`",
    difficulty: Difficulty.MEDIUM,
    points: 15,
    hints: ["nb < 0 return 0", "loop de 1 até nb"],
    solution: "int ft_iterative_factorial(int nb) { if(nb<0) return 0; int r=1; while(nb>0) r*=nb--; return r; }",
    explanation: "Fatorial usando loop.",
    tags: ["c", "piscine"],
    testCases: [{ input: "printf(\"%d\", ft_iterative_factorial(5));", expected: "120", isHidden: false }],
  },
  {
    title: "Ex 13: ft_recursive_factorial",
    slug: "ex13-ft-recursive-factorial",
    language: "c",
    description: "Fatorial recursivo.\n\n`int ft_recursive_factorial(int nb);`",
    difficulty: Difficulty.MEDIUM,
    points: 15,
    hints: ["nb * factorial(nb-1)"],
    solution: "int ft_recursive_factorial(int nb) { if(nb<0) return 0; if(nb==0) return 1; return nb * ft_recursive_factorial(nb-1); }",
    explanation: "Recursividade básica.",
    tags: ["c", "piscine"],
    testCases: [{ input: "printf(\"%d\", ft_recursive_factorial(5));", expected: "120", isHidden: false }],
  },
  {
    title: "Ex 14: ft_sqrt",
    slug: "ex14-ft-sqrt",
    language: "c",
    description: "Retorna a raiz quadrada inteira ou 0.\n\n`int ft_sqrt(int nb);`",
    difficulty: Difficulty.MEDIUM,
    points: 20,
    hints: ["i*i == nb"],
    solution: "int ft_sqrt(int nb) { if(nb<=0) return 0; int i=1; while(i*i<nb && i<46341) i++; return (i*i==nb)?i:0; }",
    explanation: "Busca linear da raiz quadrada.",
    tags: ["c", "piscine"],
    testCases: [{ input: "printf(\"%d\", ft_sqrt(16));", expected: "4", isHidden: false }],
  },
  {
    title: "Ex 15: ft_putstr",
    slug: "ex15-ft-putstr",
    language: "c",
    description: "Exibe uma string.\n\n`void ft_putstr(char *str);`",
    difficulty: Difficulty.EASY,
    points: 10,
    hints: ["while(*str)"],
    solution: "void ft_putchar(char c);\nvoid ft_putstr(char *str) { while(*str) ft_putchar(*str++); }",
    explanation: "Imprime string char por char.",
    tags: ["c", "piscine"],
    testCases: [{ input: "ft_putstr(\"42\");", expected: "42", isHidden: false }],
  },
  {
    title: "Ex 16: ft_strlen",
    slug: "ex16-ft-strlen",
    language: "c",
    description: "Retorna o tamanho da string.\n\n`int ft_strlen(char *str);`",
    difficulty: Difficulty.EASY,
    points: 10,
    hints: ["Contador até \\0"],
    solution: "int ft_strlen(char *str) { int i=0; while(str[i]) i++; return i; }",
    explanation: "Contagem de chars.",
    tags: ["c", "piscine"],
    testCases: [{ input: "printf(\"%d\", ft_strlen(\"hello\"));", expected: "5", isHidden: false }],
  },
  {
    title: "Ex 17: ft_strcmp",
    slug: "ex17-ft-strcmp",
    language: "c",
    description: "Compara duas strings.\n\n`int ft_strcmp(char *s1, char *s2);`",
    difficulty: Difficulty.MEDIUM,
    points: 15,
    hints: ["s1[i] - s2[i]"],
    solution: "int ft_strcmp(char *s1, char *s2) { while(*s1 && *s1 == *s2) { s1++; s2++; } return (unsigned char)*s1 - (unsigned char)*s2; }",
    explanation: "Comparação de string.",
    tags: ["c", "piscine"],
    testCases: [{ input: "printf(\"%d\", ft_strcmp(\"a\",\"a\"));", expected: "0", isHidden: false }],
  },
  {
    title: "Ex 18: ft_print_params",
    slug: "ex18-ft-print-params",
    language: "c",
    description: "Exibe os argumentos do programa (um por linha).\nPrecisa de main().",
    difficulty: Difficulty.MEDIUM,
    points: 15,
    hints: ["argv[i]"],
    solution: "#include <unistd.h>\nvoid ft_putchar(char c) { write(1,&c,1); }\nint main(int ac, char **av) { for(int i=1;i<ac;i++) { for(int j=0;av[i][j];j++) ft_putchar(av[i][j]); ft_putchar('\\n'); } return 0; }",
    explanation: "Uso de av e ac.",
    tags: ["c", "piscine", "program"],
    testCases: [{ input: "ARGV:hello,world", expected: "hello\nworld", isHidden: false }],
  },
  {
    title: "Ex 20: ft_strdup",
    slug: "ex20-ft-strdup",
    language: "c",
    description: "Duplica uma string com malloc.\n\n`char *ft_strdup(char *src);`",
    difficulty: Difficulty.MEDIUM,
    points: 15,
    hints: ["malloc(len+1)"],
    solution: "#include <stdlib.h>\nint ft_strlen(char *s) { int i=0; while(s[i]) i++; return i; }\nchar *ft_strdup(char *src) { char *d = malloc(ft_strlen(src)+1); if(!d) return 0; int i=0; while(src[i]) { d[i]=src[i]; i++; } d[i]=0; return d; }",
    explanation: "Alocação dinâmica.",
    tags: ["c", "piscine"],
    testCases: [{ input: "char *s = ft_strdup(\"test\"); printf(\"%s\", s); free(s);", expected: "test", isHidden: false }],
  },
  {
    title: "Ex 21: ft_range",
    slug: "ex21-ft-range",
    language: "c",
    description: "Retorna array de int de min até max (excluído).\n\n`int *ft_range(int min, int max);`",
    difficulty: Difficulty.MEDIUM,
    points: 20,
    hints: ["malloc((max-min)*sizeof(int))"],
    solution: "#include <stdlib.h>\nint *ft_range(int min, int max) { if(min>=max) return 0; int *r = malloc((max-min)*4); for(int i=0;i<max-min;i++) r[i]=min+i; return r; }",
    explanation: "Array dinâmico.",
    tags: ["c", "piscine"],
    testCases: [{ input: "int *r = ft_range(1,4); printf(\"%d %d %d\",r[0],r[1],r[2]); free(r);", expected: "1 2 3", isHidden: false }],
  },
  {
    title: "Ex 25: ft_foreach",
    slug: "ex25-ft-foreach",
    language: "c",
    description: "Aplica uma função f em cada elemento do array tab.\n\n`void ft_foreach(int *tab, int length, void (*f)(int));`",
    difficulty: Difficulty.MEDIUM,
    points: 20,
    hints: ["f(tab[i])"],
    solution: "void ft_foreach(int *tab, int length, void (*f)(int)) { for(int i=0;i<length;i++) f(tab[i]); }",
    explanation: "Function pointers.",
    tags: ["c", "piscine"],
    testCases: [{ input: "void f(int n){printf(\"%d\",n);} int t[]={1,2,3}; ft_foreach(t,3,f);", expected: "123", isHidden: false }],
  },
];

async function seed() {
  console.log("🌱 Populando todos os desafios (Piscine)...");

  await prisma.submission.deleteMany();
  await prisma.testCase.deleteMany();
  await prisma.challenge.deleteMany();

  for (const challenge of challenges) {
    const { testCases, ...challengeData } = challenge;
    await prisma.challenge.create({
      data: {
        ...challengeData,
        testCases: {
          create: testCases,
        },
      },
    });
    console.log(`✅ ${challenge.title} criado.`);
  }

  console.log("🎉 Seed completo!");
}

seed()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
